
# hardware settings
BOARD_TAG = pro328
ARDUINO_PORT = /dev/ttyUSB0

# firmware settings
MONITOR_BAUDRATE = 57600

ARDUINO_LIBS = SPI Ethernet Ethernet/utility
USER_LIB_PATH= ../../libraries

# default setting for kalin@Gentoo
MONITOR_CMD = screen
ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = ../../tools/Arduino-Makefile
AVR_TOOLS_DIR = /usr

include ${ARDMK_DIR}/Arduino.mk
